// Mock data for development and testing
export const mockProducts = [
  {
    id: "1",
    name: "iPhone 15 Pro Max",
    price: 1199,
    originalPrice: 1299,
    rating: 4.8,
    reviewCount: 2847,
    image: "/iphone-15-pro-max.png",
    category: "Smartphones",
    isNew: true,
    discount: 8,
    slug: "iphone-15-pro-max",
  },
  {
    id: "2",
    name: "MacBook Air M3",
    price: 1099,
    rating: 4.7,
    reviewCount: 1523,
    image: "/macbook-air-m3.png",
    category: "Laptops",
    isNew: true,
    slug: "macbook-air-m3",
  },
  {
    id: "3",
    name: "Nike Air Max 270",
    price: 129,
    originalPrice: 159,
    rating: 4.5,
    reviewCount: 892,
    image: "/nike-air-max-270.png",
    category: "Footwear",
    discount: 19,
    slug: "nike-air-max-270",
  },
  {
    id: "4",
    name: "Sony WH-1000XM5",
    price: 349,
    rating: 4.9,
    reviewCount: 1247,
    image: "/sony-wh-1000xm5.png",
    category: "Audio",
    slug: "sony-wh-1000xm5",
  },
  {
    id: "5",
    name: "Samsung Galaxy S24 Ultra",
    price: 1199,
    rating: 4.6,
    reviewCount: 1834,
    image: "/samsung-galaxy-s24-ultra.png",
    category: "Smartphones",
    slug: "samsung-galaxy-s24-ultra",
  },
  {
    id: "6",
    name: "Adidas Ultraboost 22",
    price: 179,
    rating: 4.4,
    reviewCount: 567,
    image: "/athletic-running-shoes.png",
    category: "Footwear",
    slug: "adidas-ultraboost-22",
  },
  {
    id: "7",
    name: "Dell XPS 13",
    price: 999,
    originalPrice: 1199,
    rating: 4.5,
    reviewCount: 743,
    image: "/dell-xps-13-laptop.png",
    category: "Laptops",
    discount: 17,
    slug: "dell-xps-13",
  },
  {
    id: "8",
    name: "Apple Watch Series 9",
    price: 399,
    rating: 4.7,
    reviewCount: 1456,
    image: "/apple-watch-series-9.png",
    category: "Accessories",
    isNew: true,
    slug: "apple-watch-series-9",
  },
  {
    id: "9",
    name: "AirPods Pro 2nd Gen",
    price: 249,
    rating: 4.6,
    reviewCount: 3421,
    image: "/airpods-pro-lifestyle.png",
    category: "Audio",
    slug: "airpods-pro-2nd-gen",
  },
  {
    id: "10",
    name: "iPad Air M2",
    price: 599,
    rating: 4.7,
    reviewCount: 1876,
    image: "/ipad-air.png",
    category: "Tablets",
    isNew: true,
    slug: "ipad-air-m2",
  },
  {
    id: "11",
    name: "PlayStation 5",
    price: 499,
    rating: 4.8,
    reviewCount: 5432,
    image: "/playstation-5-console.png",
    category: "Gaming",
    slug: "playstation-5",
  },
  {
    id: "12",
    name: "Levi's 501 Jeans",
    price: 89,
    originalPrice: 109,
    rating: 4.3,
    reviewCount: 2341,
    image: "/classic-blue-jeans.png",
    category: "Men's Fashion",
    discount: 18,
    slug: "levis-501-jeans",
  },
  {
    id: "13",
    name: "Canon EOS R6",
    price: 2499,
    rating: 4.9,
    reviewCount: 876,
    image: "/classic-canon-camera.png",
    category: "Electronics",
    slug: "canon-eos-r6",
  },
  {
    id: "14",
    name: "Zara Blazer",
    price: 129,
    rating: 4.2,
    reviewCount: 654,
    image: "/stylish-woman-in-blazer.png",
    category: "Women's Fashion",
    slug: "zara-blazer",
  },
  {
    id: "15",
    name: "Microsoft Surface Pro 9",
    price: 1299,
    rating: 4.5,
    reviewCount: 1234,
    image: "/modern-professional-workspace.png",
    category: "Laptops",
    slug: "microsoft-surface-pro-9",
  },
  {
    id: "16",
    name: "Ray-Ban Aviators",
    price: 199,
    rating: 4.6,
    reviewCount: 3456,
    image: "/placeholder-agzvc.png",
    category: "Accessories",
    slug: "ray-ban-aviators",
  },
]

export const mockCategories = [
  { id: "smartphones", name: "Smartphones", count: 45 },
  { id: "laptops", name: "Laptops", count: 32 },
  { id: "audio", name: "Audio", count: 28 },
  { id: "gaming", name: "Gaming", count: 19 },
  { id: "mens-fashion", name: "Men's Fashion", count: 67 },
  { id: "womens-fashion", name: "Women's Fashion", count: 89 },
  { id: "accessories", name: "Accessories", count: 34 },
  { id: "footwear", name: "Footwear", count: 56 },
  { id: "tablets", name: "Tablets", count: 12 },
  { id: "electronics", name: "Electronics", count: 7 },
]
